project_name: bfe

builds:
  - binary: bfe
    main: ./bfe.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm64

changelog:
  skip: true

archives:
  - id: bfe
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - conf/**/*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

release:
  disable: true
