# Copyright 2021 The BFE Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-unit-tests
    - id: go-build

- repo: git://github.com/Bahjat/pre-commit-golang
  rev: c3086eea8af86847dbdff2e46b85a5fe3c9d9656
  hooks:
    - id: go-static-check

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
    - id: markdownlint
    - id: markdownlint-fix