[Basic]
# Whether to enable OpenTelemetry (true/false)
Enabled = false

# The name of this service
ServiceName = bfe

# OTLP gRPC endpoint
Endpoint = localhost:4317

# Use insecure connection (true/false)
Insecure = true

# The rate between 0.0 and 1.0 of requests to trace
SampleRate = 1.0

[Log]
# Enable debug logging (true/false)
OpenDebug = false