[basic]
DataPath = mod_session_sticky/mod_session_sticky.data
CacheSize = 100000
CacheType = local

[redis]
# bns addr
bns = BFE.poc-redis-wx

# timeout in ms
connectTimeout = 20
readTimeout = 20
writeTimeout = 20
expireSeconds = 3600

# max idle connections
maxIdle = 20

[log]
OpenDebug = false
