
  name: test-snap-xiaofei0800
  version: git
  summary: Open-source layer 7 load balancer
  description: |
    BFE is an open-source layer 7 load balancer derived from proprietary Baidu FrontEnd.

  grade: stable
  confinement: devmode # use 'strict' once you have the right plugs and slots
  base: core18

  parts:
    bfe:
      plugin: go
      go-importpath: github.com/baidu/bfe
      source: https://github.com/baidu/bfe.git
      source-type: git
      override-build: | 
        make
        cp -r output/* $SNAPCRAFT_PART_INSTALL/

  apps:
    bfe:
      command: bin/bfe -c $SNAP/conf -l $SNAP_DATA/log
      plugs: [network-bind]
